browser=edge
# application under test
url=https://www.saucedemo.com

# common credentials - used by tests or referenced data providers
standard.user=standard_user
standard.password=secret_sauce
locked.user=locked_out_user
invalid.password=wrong_password
edge.path=C:\\drivers\\msedgedriver.exe
